#!/data/data/com.termux/files/usr/bin/bash

echo "╔════════════════════════════════════════════════════╗"
echo "║      🎮 LibGDX Development - Comandos              ║"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "📋 COMANDOS DISPONÍVEIS:"
echo ""
echo "  build     - Compila o projeto e gera o APK"
echo "              Uso: build"
echo ""
echo "  deploy    - Compila, copia para Downloads e abre"
echo "              instalador automaticamente"
echo "              Uso: deploy"
echo ""
echo "  clean     - Remove arquivos de build anteriores"
echo "              (útil quando há problemas no build)"
echo "              Uso: clean"
echo ""
echo "  sync      - Sincroniza com GitHub (pull + commit + push)"
echo "              Uso: sync"
echo ""
echo "  proj      - Navega para a pasta do projeto"
echo "              Uso: proj"
echo ""
echo "  help      - Mostra esta mensagem"
echo "              Uso: help"
echo ""
echo "════════════════════════════════════════════════════"
echo "💡 DICAS:"
echo ""
echo "  • Edite código com Acode ou Squircle CE"
echo "  • Use 'clean' se o build falhar sem motivo"
echo "  • Use 'sync' para versionar suas mudanças"
echo "  • APKs são salvos em: ~/storage/downloads/"
echo ""
echo "════════════════════════════════════════════════════"
